name: for react test

on:
  push:
    branches: ["Erick"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "impresion de prueba"
        run: echo 'impresion de prueba'
      - name: "contenido"
        run: ls -al
